# GitHub Actions workflow
name: Build and Deploy ISP490_SU25_G4 to Azure App Service

on:
  push:
    branches:
      - main  # Chạy khi có push code lên nhánh main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Bước 1: Tạo các thư mục cần thiết cho việc build
      - name: Create build directories
        run: |
          mkdir -p build/webapp/WEB-INF/classes
          mkdir -p build/webapp/WEB-INF/lib
          mkdir -p build/dist

      # Bước 2: Tải và sao chép các thư viện của dự án
      - name: Copy Library Dependencies
        run: |
          # Tải các thư viện vào thư mục lib
          curl -L -o build/webapp/WEB-INF/lib/commons-logging-1.2.jar https://repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
          curl -L -o build/webapp/WEB-INF/lib/fluent-hc-4.5.5.jar https://repo1.maven.org/maven2/org/apache/httpcomponents/fluent-hc/4.5.5/fluent-hc-4.5.5.jar
          curl -L -o build/webapp/WEB-INF/lib/gson-2.8.2.jar https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.2/gson-2.8.2.jar
          curl -L -o build/webapp/WEB-INF/lib/httpclient-4.5.5.jar https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.5/httpclient-4.5.5.jar
          curl -L -o build/webapp/WEB-INF/lib/httpcore-4.4.9.jar https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.9/httpcore-4.4.9.jar
          curl -L -o build/webapp/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.0.jar https://repo1.maven.org/maven2/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.0/jakarta.servlet.jsp.jstl-3.0.0.jar
          curl -L -o build/webapp/WEB-INF/lib/jakarta.servlet.jsp.jstl-api-3.0.2.jar https://repo1.maven.org/maven2/jakarta/servlet/jsp/jstl/jakarta.servlet.jsp.jstl-api/3.0.2.jar
          # ĐÃ XÓA DÒNG TẢI THƯ VIỆN GÂY LỖI: javaee-endorsed-api-7.0.jar
          curl -L -o build/webapp/WEB-INF/lib/javax.mail.jar https://repo1.maven.org/maven2/com/sun/mail/javax.mail/1.6.2/javax.mail-1.6.2.jar
          curl -L -o build/webapp/WEB-INF/lib/jbcrypt-0.4.jar https://repo1.maven.org/maven2/org/mindrot/jbcrypt/0.4/jbcrypt-0.4.jar
          curl -L -o build/webapp/WEB-INF/lib/mysql-connector-j-9.3.0.jar https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/9.3.0/mysql-connector-j-9.3.0.jar

      # Bước 3: Biên dịch mã nguồn Java
      - name: Compile Java code
        run: |
          find ISP490_SU25_G4/src/java -name "*.java" > sources.txt
          javac -d build/webapp/WEB-INF/classes -cp "build/webapp/WEB-INF/lib/*" @sources.txt

      # Bước 4: Sao chép các tài nguyên web (JSP, CSS, JS,...)
      - name: Copy web content
        run: cp -r ISP490_SU25_G4/web/* build/webapp/

      # Bước 5: Đóng gói thành file .war
      - name: Create WAR file
        run: |
          cd build/webapp
          jar -cvf ../dist/dongphat-crm.war .

      # Bước 6: Tải lên artifact để deploy
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: java-webapp
          path: 'build/dist/*.war'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-webapp

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dongphat-crm'
          package: '*.war'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
