# GitHub Actions workflow
name: Build and Deploy ISP490_SU25_G4 to Azure App Service

on:
  push:
    branches:
      - main  # Chạy khi có push code lên nhánh main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Ant
        run: sudo apt-get update && sudo apt-get install -y ant

      # SỬA LỖI: Chỉ định thư mục làm việc cho lệnh build
      - name: Build with Ant
        run: ant dist
        working-directory: ./ISP490_SU25_G4

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: java-webapp
          # Cập nhật lại đường dẫn tới file .war
          path: '${{ github.workspace }}/ISP490_SU25_G4/dist/*.war'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-webapp

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dongphat-crm'
          package: '*.war'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
